function PersonalInfo(props){
return(
    <div>
        <label>Name:</label>
        <input 
            onChange={props.firstNameHandler} 
            value={props.personalDetails.firstName}
        />
        <input 
            onChange={props.secondNameHandler} 
            value={props.personalDetails.secondName}
        />
        <br/>
        <label>Phone:</label>
        <input 
            onChange={props.phoneHandler} 
            value={props.personalDetails.phone}
        />
        <br/>
        <label>Gender:</label>
        <input 
            onChange={props.genderHandler} 
            value={props.personalDetails.gender}
        />
        <br/>
        <label>Email:</label>
        <input 
            onChange={props.emailHandler} 
            value={props.personalDetails.email}
        />
        <br/>
        <label>Description:</label>
        <input 
            onChange={props.descriptionHandler} 
            value={props.personalDetails.Description}
        />
    </div>
)
}
export default PersonalInfo
